// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SinSenseInfastructure;

namespace SinSense.SQLite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("SinSenseCore.Entities.Word", b =>
                {
                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.HasKey("Text");

                    b.HasIndex("Language");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("SinSenseCore.Entities.WordRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromWordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromWordText")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToWordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToWordText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromWordId");

                    b.HasIndex("FromWordText");

                    b.HasIndex("ToWordId");

                    b.HasIndex("ToWordText");

                    b.HasIndex("Type");

                    b.ToTable("WordRelations");
                });

            modelBuilder.Entity("SinSenseCore.Entities.WordRelation", b =>
                {
                    b.HasOne("SinSenseCore.Entities.Word", "FromWord")
                        .WithMany("Relations")
                        .HasForeignKey("FromWordText");

                    b.HasOne("SinSenseCore.Entities.Word", "ToWord")
                        .WithMany()
                        .HasForeignKey("ToWordText");
                });
#pragma warning restore 612, 618
        }
    }
}
